server:
  port: 10001

spring:
  application:
    name: guild-api
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #为NULL值不参与序列化
#    defaultPropertyInclusion: non_null
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  rabbitmq:
    host:
    virtual-host:
    username:
    password:
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml #这里是mapper的配置文件
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  #pagehelper分页插件
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

web:
  setting:
    common:
      sessionTimeToLive: 30d

#开启跨域处理
api:
  setting:
    cors:
      open: true