spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 30
        max-wait: 15000
        max-idle: 10
        min-idle: 1
    password:
  datasource:
    url:
    username: root
    password:

#开启跨域处理
api:
  setting:
    cors:
      open: true

upload:
  local:
    path: /work/front/upload/


logging:
  level:
    com.baomidou.example.mapper: debug


